# Generated by Django 5.1.4 on 2025-01-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tennants",
                to="tennants.house",
            ),
        ),
    ]
