# Generated by Django 5.1.3 on 2025-01-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentpayment',
            old_name='rent_month',
            new_name='current_rent_month',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='tennants.house'),
            preserve_default=False,
        ),
    ]
