# Generated by Django 5.1.3 on 2025-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0002_rename_rent_month_rentpayment_current_rent_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentpayment',
            old_name='current_rent_month',
            new_name='rent_month',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='tennant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tennant',
            name='rent_month',
        ),
        migrations.AddField(
            model_name='house',
            name='house_rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='house',
            name='house_size',
            field=models.CharField(default='1 bedroom', max_length=10),
        ),
        migrations.AddField(
            model_name='house',
            name='vacancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tennant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
