# Generated by Django 5.1.4 on 2025-01-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0003_alter_house_flat_building"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="flat_building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="tennants.flatbuilding",
            ),
        ),
    ]
