# Generated by Django 5.1.3 on 2025-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0003_rename_current_rent_month_rentpayment_rent_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='occupation_status',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='house',
            name='vacancy',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_num',
            field=models.CharField(max_length=5),
        ),
    ]
