# Generated by Django 5.1.4 on 2025-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0004_alter_house_flat_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpayment",
            name="confermation_recieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="grace_period",
            field=models.ImageField(default=5, upload_to=""),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="partial_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
