# Generated by Django 5.1.3 on 2025-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0005_alter_rentpayment_rent_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='rent_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
