# Generated by Django 5.1.4 on 2025-01-18 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0006_alter_rentpayment_rent_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="rent_due_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
