# Generated by Django 5.1.4 on 2025-02-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0006_alter_rentpayment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="id_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "rent_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="tennants.rentpayment",
                    ),
                ),
            ],
        ),
    ]
