# Generated by Django 5.1.4 on 2025-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0007_alter_tennant_rent_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tennant",
            name="email",
        ),
        migrations.AddField(
            model_name="tennant",
            name="id_number",
            field=models.CharField(default="00000000", max_length=10),
        ),
    ]
