# Generated by Django 5.1.4 on 2025-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0008_remove_tennant_email_tennant_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tennant",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
