# Generated by Django 5.1.4 on 2025-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0010_alter_tennant_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
