# Generated by Django 5.1.4 on 2025-01-21 12:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0011_alter_tennant_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
