# Generated by Django 5.1.4 on 2025-01-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0012_alter_tennant_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("number_of_houses", models.IntegerField(default=0)),
                ("how_many_occupied", models.IntegerField(default=0, editable=False)),
                ("vacant_houses", models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="house",
            name="address",
        ),
        migrations.AddField(
            model_name="house",
            name="flat_building",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="tennants.flatbuilding",
            ),
            preserve_default=False,
        ),
    ]
