# Generated by Django 5.1.4 on 2025-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0013_flatbuilding_remove_house_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="house_num",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="tennant",
            name="id_number",
            field=models.CharField(default="00000000", max_length=10, unique=True),
        ),
    ]
