# Generated by Django 5.1.4 on 2025-01-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0014_alter_house_house_num_alter_tennant_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tennant",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tennants",
                to="tennants.house",
                unique=True,
            ),
        ),
    ]
